trigger:
  branches:
    include:
      - Batch_Python_MichaelKuby

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.9'
    addToPath: true

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    black --check .
  displayName: 'Run Black formatter check'

- script: |
    pytest tests/
  displayName: 'Run tests'